# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180323_0137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Qoutelist',
        ),
    ]
