# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180328_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='qoutelist',
            name='favorite',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qoutelist',
            name='repeated_by',
            field=models.ManyToManyField(related_name='qoutelists', to='posts.User'),
        ),
    ]
