# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180328_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qoutelist',
            name='favorite',
        ),
    ]
