# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_qoutelist_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='qoutelist',
            name='favorite',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
