# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20180328_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qoutelist',
            name='itemname2',
        ),
    ]
